# 顶部导航（宽屏时显示在左侧栏里，窄屏是顶部横向菜单）

[[main]]
    name   = "Archives"
    url    = "/archives/"
    weight = 10

[[main]]
    name   = "Categories"
    url    = "/categories/"
    weight = 20

[[main]]
    name   = "CV"
    url    = "/cv/"
    weight = 30

[[main]]
    name   = "About"
    url    = "/about/"
    weight = 40
